blueprint:
  name: FOH Switch via Zigbee2MQTT
  description: >
    Brug Friends of Hue (EnOcean/PTM215Z) via Zigbee2MQTT.
    Lytter på MQTT action-events og mapper til handlinger.
  domain: automation
  input:
    foh_topic:
      name: FOH MQTT topic
      description: Zigbee2MQTT topic for FOH switch (slutter med /action)
      default: zigbee2mqtt/foh_switch/action
      selector:
        text:

    button_1_press:
      name: Button 1 Press
      default: []
      selector:
        action: {}
    button_2_press:
      name: Button 2 Press
      default: []
      selector:
        action: {}
    button_3_press:
      name: Button 3 Press
      default: []
      selector:
        action: {}
    button_4_press:
      name: Button 4 Press
      default: []
      selector:
        action: {}

    button_1_hold:
      name: Button 1 Hold
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Button 2 Hold
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Button 3 Hold
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Button 4 Hold
      default: []
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: !input foh_topic

variables:
  action: "{{ trigger.payload }}"

action:
  - choose:
      - conditions: "{{ action == 'press_1' }}"
        sequence: !input button_1_press
      - conditions: "{{ action == 'press_2' }}"
        sequence: !input button_2_press
      - conditions: "{{ action == 'press_3' }}"
        sequence: !input button_3_press
      - conditions: "{{ action == 'press_4' }}"
        sequence: !input button_4_press

      - conditions: "{{ action == 'hold_1' }}"
        sequence: !input button_1_hold
      - conditions: "{{ action == 'hold_2' }}"
        sequence: !input button_2_hold
      - conditions: "{{ action == 'hold_3' }}"
        sequence: !input button_3_hold
      - conditions: "{{ action == 'hold_4' }}"
        sequence: !input button_4_hold

mode: queued
max: 10
